<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tkdiffbot">
    <xacro:property name="base_link_length" value="0.08"/>
    <xacro:property name="base_link_radius" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_length" value="0.015"/>
    <xacro:property name="support_wheel" value="0.0075"/>
    <xacro:property name="earth_space" value="0.015" />

    <material name="yellow">
        <color rgba="0.8 0.3 0.1 1.0" />
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 0.8"/>
    </material>

    <!-- base_footprint  -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
        </visual>
    </link>
    <!-- base_link -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.08"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.08"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.0122666" ixy="0" ixz="0" iyy="0.0122666" iyz="0" izz="0.02"/>
        </inertial>
    </link>

    <joint name="base_link2base_footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.055"/>
    </joint>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
            <material name="black"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.000190416666667" ixy="0" ixz="0" iyy="0.0001904" iyz="0" izz="0.00036"/>
        </inertial>
    </link>
    
    <joint name="left_wheel2base_link" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.1 -0.0225" />
        <axis xyz="0 1 0"/>
    </joint>
    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="black"/>
        </collision>
    </link>

    <joint name="right_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="0 -0.1 -0.0225" />
        <axis xyz="0 1 0" />
    </joint>
    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    
    <link name="front_wheel">
        <visual>
            <geometry>
                <sphere radius="${support_wheel}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${support_wheel}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black"/>
        </collision>
        <inertial>
            <mass value="0.02"/>
            <inertia ixx="0.000190416666667" ixy="0" ixz="0" iyy="0.0001904" iyz="0" izz="0.00036"/>
        </inertial>
    </link>
    

    <joint name="front_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="front_wheel" />
        <origin xyz="${base_link_radius - wheel_radius} 0 ${-(base_link_length /2 + earth_space /2)}" />
        <axis xyz="1 1 1" />
    </joint>

    <gazebo reference="front_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="front_wheel">
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
        <kp value="1000000.0" />
        <kd value="10.0" />
        <!-- <fdir1 value="0 0 1"/> -->
    </gazebo>

    <link name="back_wheel">
        <visual>
            <geometry>
                <sphere radius="${support_wheel}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${support_wheel}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black"/>
        </collision>
        <inertial>
            <mass value="0.02"/>
            <inertia ixx="0.000190416666667" ixy="0" ixz="0" iyy="0.0001904" iyz="0" izz="0.00036"/>
        </inertial>
    </link>

    <joint name="back_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="back_wheel" />
        <origin xyz="${-(base_link_radius - wheel_radius)} 0 ${-(base_link_length /2 + earth_space /2)}" />
        <axis xyz="1 1 1" />
    </joint>

    <gazebo reference="back_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="back_wheel">
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
        <kp value="1000000.0" />
        <kd value="10.0" />
        <!-- <fdir1 value="0 0 1"/> -->
    </gazebo>

    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
            <ros>
            <namespace>/</namespace>
            <remapping>cmd_vel:=cmd_vel</remapping>
            <remapping>odom:=odom</remapping>
            </ros>
            <update_rate>30</update_rate>
            <!-- wheels -->
            <!-- <left_joint>left_wheel_joint</left_joint> -->
            <!-- <right_joint>right_wheel_joint</right_joint> -->
            <left_joint>left_wheel2base_link</left_joint>
            <right_joint>right_wheel2base_link</right_joint>
            <!-- kinematics -->
            <wheel_separation>0.2</wheel_separation>
            <wheel_diameter>0.065</wheel_diameter>
            <!-- limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>false</publish_wheel_tf>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
        <plugin name="tkbot_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
                <remapping>~/out:=joint_states</remapping>
            </ros>
            <update_rate>30</update_rate>
            <joint_name>right_wheel2base_link</joint_name>
            <joint_name>left_wheel2base_link</joint_name>
        </plugin> 
    </gazebo>

    <!-- camera -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="0.01 0.025 0.025"/>
            </geometry>
        </visual>
    </link>
    <joint name="camera2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="0.08 0.0 0.0525" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- lidar -->
    <link name="laser">
        <visual>
            <geometry>
                <!-- <cylinder radius="0.03" length="0.04"/> -->
                <mesh filename="package://tkdiffbot/mesh/diff_2w/laser_link.STL" />
            </geometry>
            <material name="black"/>
        </visual>
    </link>
    <gazebo reference="camera">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="laser2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="0.0 0.0 0.08" rpy="0.0 0.0 0.0"/>
    </joint>
    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="laser">
      <sensor name="laser_sensor" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>5</update_rate>
      <pose>0 0 0.075 0 0 0</pose>
      <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1.000000</resolution>
              <min_angle>0.000000</min_angle>
              <max_angle>6.280000</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.120000</min>
            <max>3.5</max>
            <resolution>0.015000</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
      </ray>

      <plugin name="laserscan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <!-- <namespace>/tb3</namespace> -->
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser</frame_name>
      </plugin>
      </sensor>
    </gazebo>
    
</robot>